@startuml
set separator none
title SocialBankingApplication

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("SocialBankingApplication.SocialBankingApplication_boundary", "SocialBankingApplication", $tags="") {
  Component(SocialBankingApplication.SocialBankingApplication.CustomerModule, "Customer Module", $techn="Module", $descr="", $tags="", $link="")
  Component(SocialBankingApplication.SocialBankingApplication.CommonModule, "Common Module", $techn="Module", $descr="", $tags="", $link="")
  Component(SocialBankingApplication.SocialBankingApplication.AuthenticationModule, "Authentication Module", $techn="Module", $descr="", $tags="", $link="")
  Component(SocialBankingApplication.SocialBankingApplication.AppConfigModule, "App Config Module", $techn="Module", $descr="", $tags="", $link="")
  Component(SocialBankingApplication.SocialBankingApplication.TransactionModule, "Transaction Module", $techn="Module", $descr="", $tags="", $link="")
  Component(SocialBankingApplication.SocialBankingApplication.AccountModule, "Account Module", $techn="Module", $descr="", $tags="", $link="")
  Component(SocialBankingApplication.SocialBankingApplication.DashboardModule, "Dashboard Module", $techn="Module", $descr="", $tags="", $link="")
}

Rel(SocialBankingApplication.SocialBankingApplication.DashboardModule, SocialBankingApplication.SocialBankingApplication.AuthenticationModule, "listens to", $techn="", $tags="", $link="")
Rel(SocialBankingApplication.SocialBankingApplication.DashboardModule, SocialBankingApplication.SocialBankingApplication.CommonModule, "depends on", $techn="", $tags="", $link="")
Rel(SocialBankingApplication.SocialBankingApplication.DashboardModule, SocialBankingApplication.SocialBankingApplication.CustomerModule, "uses", $techn="", $tags="", $link="")
Rel(SocialBankingApplication.SocialBankingApplication.DashboardModule, SocialBankingApplication.SocialBankingApplication.AccountModule, "uses", $techn="", $tags="", $link="")
Rel(SocialBankingApplication.SocialBankingApplication.AppConfigModule, SocialBankingApplication.SocialBankingApplication.CommonModule, "depends on", $techn="", $tags="", $link="")
Rel(SocialBankingApplication.SocialBankingApplication.AccountModule, SocialBankingApplication.SocialBankingApplication.CommonModule, "depends on", $techn="", $tags="", $link="")
Rel(SocialBankingApplication.SocialBankingApplication.AccountModule, SocialBankingApplication.SocialBankingApplication.TransactionModule, "uses", $techn="", $tags="", $link="")
Rel(SocialBankingApplication.SocialBankingApplication.AuthenticationModule, SocialBankingApplication.SocialBankingApplication.CommonModule, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml